openapi: 3.1.0
info:
  title: Enrollment APIs
  description: Creating new enrollments and updating existing enrollments
  version: 1.0.0
  contact:
    url: https://www.govstack.global/
paths:
  /enrollment:
    put:
      description: Create user enrollment
      requestBody:
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/enrollmentRequest'
      responses: 
        200:
          description: Successfully enrolled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/enrollmentResponse'
        201:
          description: New user enrolled successfully.
        401:
          description: Unauthorized
        403:
          description: Not Found
        404:
          description: Not Found
components:
  schemas:
    enrollmentRequest:
      type: object
      properties:
        id:
          type: string
          example: govstack.enrollment
        version:
          type: string
          example: v1
        requesttime:
          type: string
          example: 2022-06-06T13:24:50.605Z
        request:
          type: object
          properties:
            offlineMode:
              type: boolean
              example: false
            id:
              type: string
              deault: 10001100020010120230704042404
            refId:
              type: string
              deafult: 10001_10002
            fields:
              type: object
              properties:
                gender:
                  type: string
                  example: '[ { "language" : "eng", "value" : "Male" } ]'
                city:
                  type: string
                  example: '[ { "language" : "eng", "value" : "Kenitra" } ]'
                postalCode:
                  type: string
                  example: 14022
                fullName:
                  type: string
                  example: '[ { "language" : "eng", "value" : "Enrollment89 I290" } ]'
            metaInfo:
              type: object
              properties:
                metaData:
                  type: string
                  example: '[ { label" : "centerId", "value" : "10001" }, { "label" : "machineId", "value" : "10002" } ]'
                capturedRegisteredDevices:
                    type: string
                    example: '[]'
                operationsData:
                  type: string
                  example: '[ { "label": "officerId", "value": "globaladmin" }, { "label" : "officerBiometricFileName","value":null } ]'
            process:
              type: string
              example: NEW
            source:
              type: string
              example: REGISTRATION_CLIENT
            audits:
              type: array
              items:
                properties:
                  name:
                    type: string
                  value:
                    type: string
              example: 
                - eventId: RPR_405
                  hostName: Techno-367
                  idType: REGISTRATION_ID
                  hostIp: 192.168.1.100
            biometrics:
              type: object
              properties:
                version: 
                  type: object
                  properties:
                    major:
                      type: integer
                    minor:
                       type: integer
                cbeffversion:
                  type: object
                  properties:
                    major:
                      type: integer
                    minor:
                       type: integer
                birInfo:
                  type: object
                  properties:
                    creator:
                      type: string
                    index:
                      type: string
                    payload:
                      type: array
                      items:
                        properties:
                          type: string
                      example:
                        - payload
                    integrity:
                      type: boolean
                    creationDate:
                      type: string
                    notValidBefore:
                      type: string
                    notValidAfter:
                      type: string
                segment:
                  type: array
                  items:
                    properties:
                      version:
                        type: object
                        properties:
                          major:
                            type: integer
                            example: 1
                          minor:
                            type: integer
                      cbeffversion:
                        type: object
                        properties:
                          major:
                            type: integer
                          minor:
                            type: integer
                      birInfo:
                        type: object
                        properties:
                          creator:
                            type: string
                          index:
                            type: string
                          payload:
                            type: array
                          integrity:
                            type: boolean
                          creationDate:
                            type: string
                          notValidBefore:
                            type: string
                          notValidAfter:
                            type: string
                      bdbInfo:
                        type: object
                        properties:
                          challengeResponse:
                            type: array
                          index:
                            type: string
                          format:
                            type: object
                            properties:
                              organization:
                                type: string
                              type:
                                type: string
                          encryption: 
                            type: boolean
                          creationDate:
                            type: string
                            example: 2023-05-03T11:04:05.0166982
                          notValidBefore:
                            type: string
                          notValidAfter:
                            type: string
                          type:
                            type: array
                            items:
                              properties:
                                value:
                                  type: string
                                  enum: [FACE FINGER IRIS]
                            example: 
                              - FINGER
                          subtype:
                            type: array
                            items:
                            example:
                              - Left
                              - LittleFinger
                          level:
                            type: string
                            enum: [RAW INTERMEDIATE PROCESSED]
                            example: RAW
                          product:
                            type: object
                            properties:
                              organization:
                                type: string
                              type:
                                type: string
                          captureDevice:
                            type: object
                            properties:
                              organization:
                                type: string
                              type:
                                type: string
                          featureExtractionAlgorithm:
                            type: object
                            properties:
                              organization:
                                type: string
                              type:
                                type: string
                          comparisonAlgorithm:
                            type: object
                            properties:
                              organization:
                                type: string
                              type:
                                type: string
                          compressionAlgorithm:
                            type: object
                            properties:
                              organization:
                                type: string
                              type:
                                type: string
                          purpose:
                            type: string
                            enum: [VERIFY IDENTIFY ENROLL ENROLLVERIFY ENROLLIDENTIFY AUDIT]
                          quality:
                            type: object
                            properties:
                              algorithm:
                                type: object
                                properties:
                                  organization:
                                    type: string
                                  type: 
                                    type: string
                              score: 
                                type: integer
                              qualityCalculationFailed:
                                type: string
                      bdb:
                        type: array
                        items:
                          properties:
                            type: string
                        example:
                          - string
                      sb:
                        type: array
                        items:
                          properties:
                            type: string
                        example: 
                          - string
                      birs:
                        type: array
                        items:
                           properties:
                           type: object
                        example:
                          - {}
                      sbInfo:
                        type: object
                        properties:
                          format:
                            type: object
                            properties:
                              organization:
                                type: string
                              type:
                                type: string
                      others:
                        type: object
                others:
                  type: object
            documents:
              type: object
    enrollmentResponse:
      type: object
      properties:
        id:
          type: string
        version:
          type: string
        responsetime: 
          type: string
        metaData:
          type: object
          properties:
            data:
              type: string
        response:
          type: array
          items:
            properties:
              id:
                type: string
              packetName:
                type: string
              source:
                type: string
              process:
                type: string
              refId:
                type: string
              schemaVersion:
                type: string
              signature:
                type: string
              encryptedHash:
                type: string
              providerName:
                type: string
              providerVersion:
                type: string
              creationDate:
                type: string
        errors:
          type: array
          items:
            properties:
              errorCode:
                type: string
              message:
                type: string